#ifndef __CLIENT_ERRORCODES_H__
#define __CLIENT_ERRORCODES_H__

#define CMD_ERROR_SUCCESS 100
#define CMD_ERROR_INVALID_COMMAND 101
#define CMD_ERROR_INVALID_ARGUMENTS 102
#define CMD_ERROR_INVALID_ARGUMENTS_COUNT 103
#define CMD_ERROR_INVALID_ARGUMENTS_TYPE 104
#define CMD_ERROR_SEND_FAILED 105
#define CMD_ERROR_RECV_FAILED 106

#endif // __CLIENT_ERRORCODES_H__